server:
  port: 18082
  servlet:
    path: /callback-fit
spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true

  activemq:
    ActiveMQTopic: nm_topic_test
    ActiveMQQueue: nm_queue_test
    user: admin
    password: admin
    broker-url: tcp://192.168.0.69:61616
    pool:
      enabled: true
      max-connections: 10
      #空闲的连接过期时间，默认为30秒
#      idle-timeout: 30s

mybatis-plus:
  # 指定全局配置文件位置
  configLocation: classpath:mybatis/mybatis-cfg.xml
  # 指定sql映射文件位置
  mapperLocations: classpath:mybatis/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.soholy.cb.entity
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.soholy.cb.enums

  #conf
  globalConfig:
     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
     id-type: 0
     #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
     field-strategy: 2
     #驼峰下划线转换
     db-column-underline: true
     #刷新mapper 调试神器
     refresh-mapper: true
     #数据库大写下划线转换
     capital-mode: true
     #序列接口实现类配置
     #key-generator: com.baomidou.springboot.xxx
     #逻辑删除配置（下面3个配置）
     logic-delete-value: 0
     logic-not-delete-value: 1
     #自定义SQL注入器
     #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
     #自定义填充策略接口实现
     #meta-object-handler: com.baomidou.springboot.xxx
     configuration:
       mapUnderscoreToCamelCase: true
       cacheEnabled: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT VERSION(), @@sql_mode
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
#   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

